//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.CustomsDeclarationService40 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomsDeclarationService40.ICustomsDeclarationService")]
    public interface ICustomsDeclarationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomsDeclarationService/DoWork", ReplyAction="http://tempuri.org/ICustomsDeclarationService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomsDeclarationService/DoWork", ReplyAction="http://tempuri.org/ICustomsDeclarationService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomsDeclarationService/CustomsDeclarationQuery", ReplyAction="http://tempuri.org/ICustomsDeclarationService/CustomsDeclarationQueryResponse")]
        string CustomsDeclarationQuery(string TradeCode, string DateFrom, string Dateto, string EntryNo, string GoodsName, string page_index, string page_size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomsDeclarationService/CustomsDeclarationQuery", ReplyAction="http://tempuri.org/ICustomsDeclarationService/CustomsDeclarationQueryResponse")]
        System.Threading.Tasks.Task<string> CustomsDeclarationQueryAsync(string TradeCode, string DateFrom, string Dateto, string EntryNo, string GoodsName, string page_index, string page_size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomsDeclarationService/getDeh", ReplyAction="http://tempuri.org/ICustomsDeclarationService/getDehResponse")]
        string getDeh(string EntryNo, string tradeCo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomsDeclarationService/getDeh", ReplyAction="http://tempuri.org/ICustomsDeclarationService/getDehResponse")]
        System.Threading.Tasks.Task<string> getDehAsync(string EntryNo, string tradeCo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomsDeclarationServiceChannel : WindowsFormsApp2.CustomsDeclarationService40.ICustomsDeclarationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomsDeclarationServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp2.CustomsDeclarationService40.ICustomsDeclarationService>, WindowsFormsApp2.CustomsDeclarationService40.ICustomsDeclarationService {
        
        public CustomsDeclarationServiceClient() {
        }
        
        public CustomsDeclarationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomsDeclarationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomsDeclarationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomsDeclarationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string CustomsDeclarationQuery(string TradeCode, string DateFrom, string Dateto, string EntryNo, string GoodsName, string page_index, string page_size) {
            return base.Channel.CustomsDeclarationQuery(TradeCode, DateFrom, Dateto, EntryNo, GoodsName, page_index, page_size);
        }
        
        public System.Threading.Tasks.Task<string> CustomsDeclarationQueryAsync(string TradeCode, string DateFrom, string Dateto, string EntryNo, string GoodsName, string page_index, string page_size) {
            return base.Channel.CustomsDeclarationQueryAsync(TradeCode, DateFrom, Dateto, EntryNo, GoodsName, page_index, page_size);
        }
        
        public string getDeh(string EntryNo, string tradeCo) {
            return base.Channel.getDeh(EntryNo, tradeCo);
        }
        
        public System.Threading.Tasks.Task<string> getDehAsync(string EntryNo, string tradeCo) {
            return base.Channel.getDehAsync(EntryNo, tradeCo);
        }
    }
}
